[package]
name = "hello_cairo"
version = "0.1.0"
edition = "2023_11"
readme = "README.md"


[dependencies]
starknet = "2.6.3"

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.22.0" }

[[target.starknet-contract]]
casm = true
sierra = true
